# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Ant On Y
tagline:             ''
description:         'a programmer in love with machine learning and speech recognition.'
url:                 http://antosny.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Antosny
  url:               https://weibo.com/antosny
  email:             xieruiming08@gmail.com

# Custom vars
version:             1.0.0

gems:
  - jekyll-paginate
  - jekyll-gist